export const CONTENT_MESSAGE = {
  CONTENT_REGISTER: "CONTENT_REGISTER",
  SCAN_PAGE: "SCAN_PAGE",
  SCAN_SELECTION: "SCAN_SELECTION",
  ENRICH_SELECTION: "ENRICH_SELECTION",
  NAVIGATE_TO_IOC_ANCHOR: "NAVIGATE_TO_IOC_ANCHOR",
  REOPEN_INVESTIGATION_HISTORY: "REOPEN_INVESTIGATION_HISTORY",
  TOGGLE_WORKSPACE: "TOGGLE_WORKSPACE",
  OPEN_WORKSPACE: "OPEN_WORKSPACE",
  TOGGLE_COMMAND_PALETTE: "TOGGLE_COMMAND_PALETTE",
} as const;
