export const CONTENT_MESSAGE = {
  CONTENT_REGISTER: "CONTENT_REGISTER",
  SCAN_PAGE: "SCAN_PAGE",
  SCAN_SELECTION: "SCAN_SELECTION",
  ENRICH_SELECTION: "ENRICH_SELECTION",
  NAVIGATE_TO_IOC_ANCHOR: "NAVIGATE_TO_IOC_ANCHOR",
  TOGGLE_WORKSPACE: "TOGGLE_WORKSPACE",
  OPEN_WORKSPACE: "OPEN_WORKSPACE",
} as const;
