/**
 * Phase 21D — adapter constant type (mutable copy of SCORING_CALIBRATION shape).
 */

export type ScoringAdapterConstants = {
  MATCH_CONFIRMED_RISK: number;
  MATCH_DEFAULT_CONFIDENCE: number;
  MATCH_NO_HIT_RISK: null;
  VT_SUSPICIOUS_COEFFICIENT: number;
  VT_EXPLICIT_HARMLESS_CONFIDENCE: number;
  VT_UNDETECTED_ONLY_CONFIDENCE: number;
  VT_STRONG_MALICIOUS_CONFIDENCE: number;
  VT_DETECTION_CONFIDENCE_BASE: number;
  VT_DETECTION_CONFIDENCE_PER_ENGINE: number;
  OTX_PULSE_SATURATION: number;
  OTX_PULSE_BASE_CONFIDENCE: number;
  OTX_FAMILY_CONFIDENCE_BOOST: number;
  OTX_ATTACK_CONFIDENCE_BOOST: number;
  URLSCAN_MALICIOUS_RISK: number;
  URLSCAN_MALICIOUS_CONFIDENCE: number;
  URLSCAN_SUSPICIOUS_RISK: number;
  URLSCAN_SUSPICIOUS_CONFIDENCE: number;
  GREYNOISE_MALICIOUS_RISK: number;
  GREYNOISE_MALICIOUS_CONFIDENCE: number;
  GREYNOISE_BENIGN_RISK: number;
  GREYNOISE_BENIGN_CONFIDENCE: number;
  GREYNOISE_RIOT_BENIGN_CONFIDENCE: number;
  ABUSEIPDB_BASE_CONFIDENCE: number;
  ABUSEIPDB_REPORT_CONFIDENCE_BOOST_CAP: number;
  ABUSEIPDB_ZERO_CONFIDENCE: number;
  CONTEXT_RISK: null;
  CONTEXT_CONFIDENCE: number;
};
